import ProjectPage from "../projectpage"

function Trolley() {
  return (
    <ProjectPage
      title="Intelligent Trolley Assistant"
      category="Personal Project"
      description="Mechatronic embedded system integrated into a trolley to help load transportation for people with strength and ability limitations."
      image="/src/assets/projects/image.jpg"
      video="/src/assets/projects/video.mp4"
    >

      <section className="documentation-section">

        <h2>Project Overview</h2>

        <p>
          The objective of this project is to enhance the utility of a trolley in daily use. 
          It is oriented towards effort assistance in order to obtain a dynamically stable moving 
          platform without transferring the load to the user. 
          
        </p>

        <i>For the personal story, this project idea came from the difficulties my mother, affected by severe obesity, 
          has encountered when our elevator ran out of service and none of us were physically nearby to help her.</i>

      </section>


      <section className="documentation-section">

        <h2>Engineering Approach</h2>

        <p>
         The system has been thaught to integrate a propulsion motor generated by mechanical stimulation, obstacle detection, 
         increase stability for quasi-autosufficient load transportation and motion. To ease conditions of use,
         additional electronical functionalities has also been integrated such as emergency stop, directional buttons, obstacle procedure button.
         One of the main engineering challenge  is to manage stair-climbing procedure, with minimum human effort.
        </p> 
        
        <p>The requirements are as follows :<br/>
        -gearmotor for motion<br/>
        -force sensor as mechanical stimulation for motor activation<br/>
        -ESP 32 for Human-Machine-Interface, linking the buttons to actual commands on the motor.
        ...

        </p>

      </section>


      <section className="documentation-section">

        <h2>Development</h2>

        <p>
          nanana.
        </p>

      </section>

      <section className="documentation-section">

        <h2>Mechanical Aspect</h2>

        <p>
          nanana.
        </p>

      </section>

      <section className="documentation-section">

        <h2>Electronical Aspect</h2>

        <p>
          nanana.
        </p>

      </section>


      <section className="documentation-section">

        <h2>Results</h2>

        <i>
          The results are not available for the moment, but will be published soon. 
        To be notified by the progress of this project, don't hesitate to take a look at my LinkedIn profile.
        
        <br/><br/>
        <a
          href="https://linkedin.com/in/chaymarouaa"
          target="_blank"
          rel="noreferrer"
        >
          Click here to see Chayma Rouaa Linkedin profile
        </a>
        </i>

      </section>


      <section className="documentation-section">

        <h2>Challenges</h2>

        <p>
         1/ The first challenge was to change the Weight transfer that usually goes partly to the user, into the system 
         to self-support its whole weight without sacrificing the stability of this dynamic system. 
         <br/><br/><em>One of the solutions was to add an elevated wheel that would hold the weight that the user usually carries. 
         It would create a sort of "lambda" form from side profile. Also, the obstacle sensor would be placed at the wheel 
         area to detect stairs and other elevated obstacles.</em>
         <br/>
         <br/>
         2/ The second engineering challenge was to manage stair-climbing procedure, with minimum human effort.
        </p>

      </section>

      <section className="documentation-section">

        <h2>Improvements</h2>

        <p>
        </p>

      </section>

    </ProjectPage>
  )
}

export default Trolley
